### ISSUE TITLE
Crash when buying wildfire joker or selling card after buying it (working correctly on 1.2.0a)

### ISSUE THREAD

**Issue by G48sddsdsdsd** [SDM0/Joker-Evolution#3]
new to github, just made account to report this, so maybe not the right place to write it in.

Oops! The game crashed:
[SMODS joker_evolution "functions.lua"]:177: attempt to index a nil value

Additional Context:
Balatro Version: 1.0.1m-FULL
Modded Version: 1.0.0~ALPHA-1122a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Joker Evolution by SDM_0 [ID: joker_evolution, Priority: -1000, Version: 1.2.1a, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'calculate_evo' at file 'functions.lua:177' (from mod with id joker_evolution)
Local variables:
 self = table: 0x0f2c8c08  {tilt_var:table: 0x0f0586d8, click_offset:table: 0x0f4ea088, zoom:true, children:table: 0x0f020b18 (more...)}
 context = table: 0x0f33fc28  {retrigger_joker_check:true, other_context:table: 0x0f98f768, other_card:table: 0x0f2c8c08 (more...)}
 obj = table: 0x0f5223b8  {alerted:false, _saved_d_u:true, unlocked:true, _u:true, rarity:3, _discovered_unlocked_overwritten:true (more...)}
 evol = table: 0x0f07e860  {amount:15, carry_stat:table: 0x0f0bc9f8, key:j_campfire, evo:j_evo_Wildfire (more...)}
 (*temporary) = nil
 (*temporary) = string: "j_evo_Wildfire"
 (*temporary) = table: 0x0f0869a8  {1:table: 0x0f348c70, 2:table: 0x0f1aceb8, 3:table: 0x0eec99f8, 4:table: 0x0f49cbc0 (more...)}
 (*temporary) = number: 12
 (*temporary) = string: "attempt to index a nil value"
(4) Lua method 'calculate_joker' at file 'overrides.lua:52' (from mod with id joker_evolution)
Local variables:
 self = table: 0x0f2c8c08  {tilt_var:table: 0x0f0586d8, click_offset:table: 0x0f4ea088, zoom:true, children:table: 0x0f020b18 (more...)}
 context = table: 0x0f33fc28  {retrigger_joker_check:true, other_context:table: 0x0f98f768, other_card:table: 0x0f2c8c08 (more...)}
 ret = nil
(5) Lua upvalue 'calculate_jokerref' at Steamodded file 'core/overrides.lua:2103' 
Local variables:
 self = table: 0x0f2c8c08  {tilt_var:table: 0x0f0586d8, click_offset:table: 0x0f4ea088, zoom:true, children:table: 0x0f020b18 (more...)}
 context = table: 0x0f98f768  {selling_card:true, card:table: 0x0f16dfb0}
 ret = table: 0x0fa8f0e0  {joker_repetitions:table: 0x0f6853b8}
 triggered = boolean: true
 _ret = nil
 (for index) = number: 1
 (for limit) = number: 5
 (for step) = number: 1
 i = number: 1
(6) Lua method 'calculate_joker' at file 'overrides.lua:50' (from mod with id joker_evolution)
Local variables:
 self = table: 0x0f2c8c08  {tilt_var:table: 0x0f0586d8, click_offset:table: 0x0f4ea088, zoom:true, children:table: 0x0f020b18 (more...)}
 context = table: 0x0f98f768  {selling_card:true, card:table: 0x0f16dfb0}
(7) Lua function '?' at file 'functions/button_callbacks.lua:2375' (best guess)
Local variables:
 e = table: 0x0f7dcc98  {pixellated_rect:table: 0x0efa7098, click_offset:table: 0x0f2f2800, children:table: 0x0f0c4da0 (more...)}
 card = table: 0x0f16dfb0  {click_offset:table: 0x0f27a0c8, static_rotation:false, ambient_tilt:0.2 (more...)}
 (for index) = number: 1
 (for limit) = number: 5
 (for step) = number: 1
 i = number: 1
(8) Lua method 'click' at file 'engine/ui.lua:981'
Local variables:
 self = table: 0x0f7dcc98  {pixellated_rect:table: 0x0efa7098, click_offset:table: 0x0f2f2800, children:table: 0x0f0c4da0 (more...)}
(9) Lua method 'update' at file 'engine/controller.lua:375'
Local variables:
 self = table: 0x0f1ef418  {held_button_times:table: 0x0f21cd38, focus_cursor_stack_level:1, snap_cursor_to:table: 0x0f63e460 (more...)}
 dt = number: 0.0100506
(10) Lua upvalue 'gameUpdateRef' at file 'game.lua:2635'
Local variables:
 self = table: 0x0efbda90  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0fa317c8 (more...)}
 dt = number: 0.0100506
(11) Lua method 'update' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x0efbda90  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0fa317c8 (more...)}
 dt = number: 0.0100506
(12) Lua field 'update' at file 'main.lua:965'
Local variables:
 dt = number: 0.0100506
(13) Lua function '?' at file 'main.lua:909' (best guess)
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 880 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by SDM0** [comment]
Hey, thank you for the report, I've updated the mod with a fix, let me know if it solves the issue.
